### PR TITLE
Fixed whitespace issues. You're welcome.

### PR DESCRIPTION
**Pull request by brandon1024**
Ye

### CODE REVIEW

**Comment by jsmith** [comment]
Love this :heart:

**Comment by brandon1024** [comment]
:relieved: I'm just concerned it's going to have nasty conflicts with the work @tonerm43 and @mwalz1 are doing :(

**Comment by jsmith** [comment]
Yeah better wait a bit! This was all automated, right?

**Comment by brandon1024** [comment]
Mostly! I can wait until they get their stuff in, and then just rebase off them

**Pull request merged**
